env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  "react/prop-types": 0,
  "react/jsx-props-no-spreading": 0,
  "implicit-arrow-linebreak": 0,
  "import/prefer-default-export": 0,
  "react/jsx-filename-extension": 0
}
